function(add_q1_schema TARGET)
    set(options)
    set(oneValueArgs SOURCE ROOT)
    set(multiValueArgs FILES)
    cmake_parse_arguments(Q1 "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    message(STATUS "Q1 (stub): ${TARGET}")
    if(NOT Q1_ROOT)
        set(Q1_ROOT "${CMAKE_CURRENT_LIST_DIR}")
    endif()

    set(Q1_RESOLVED_FILES)
    foreach(Q1_FILE IN LISTS Q1_FILES)
        if(IS_ABSOLUTE "${Q1_FILE}")
            get_filename_component(Q1_ABS_FILE "${Q1_FILE}" ABSOLUTE)
        else()
            get_filename_component(Q1_ABS_FILE "${Q1_FILE}" ABSOLUTE BASE_DIR "${Q1_ROOT}")
        endif()
        list(APPEND Q1_RESOLVED_FILES "${Q1_ABS_FILE}")
    endforeach()

    message(STATUS "  root: ${Q1_ROOT}")
    message(STATUS "  files:")
    foreach(Q1_ABS_FILE IN LISTS Q1_RESOLVED_FILES)
        message(STATUS "    ${Q1_ABS_FILE}")
    endforeach()
    message(STATUS "  source: ${Q1_SOURCE}")
endfunction()
